### ISSUE TITLE
Standardize  UI handler functions naming 

### ISSUE THREAD

**Issue by jpabadir** [john-and-jaden/outbreak-simulator#9]
Currently, we have UpdateTimescale(), ShowInfectionRadius(), and SetNumPeople() which all handle UI elements changes. We should standardize their naming.

**Comment by JadenBalogh** [comment]
What is your preference? I think SetXyzAbc is good for anything where we are passing a new value which should replace the old value. UpdateXyzAbc is good for anything where we just notifying the controller that it should update a certain value, without actually passing any parameter necessarily.

**Comment by jpabadir** [comment]
So any UI function is going to be SetXyzAbc(), right? Because we're (almost) always passing a parameter if we're chaning something from the UI.

**Comment by JadenBalogh** [comment]
Yeah, for user inputs it'll likely be a set. For buttons and such, probably not.

**Comment by jpabadir** [comment]
Okay, sounds to me to have a mix of SetXyzAbc() and UpdateXyzAbc(), depending on whether we are passing parameters or not.

**Comment by jpabadir** [comment]
I'm happy to go through and change the ones we already have tonight (but be my guest if you want to do it).

**Comment by JadenBalogh** [comment]
Sure, go for it.
